name: screenshots ci actions
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@2ad059691ebf58ff647cd312184d32e5fd400074 # pin version prior to hang issues
      env:
        CI: 'true'

    # SG waldbrand
    - name: screenshots-ci-action
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://visualize.admin.ch/de/v/4lPHCdjPS8Se

    # upload
    - uses: actions/upload-artifact@v4 # Uplaod screenshots to Actions Artifacts via actions/upload-artifact@v2
      with:
        path: screenshots
        name: screenshots
        retention-days: 30
