name: Take Homepage Screenshot


on:
  push:
    branches:
      - main

  #schedule:
  #  - cron: "*/5 * * * *"
  #workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # We use our own token for pushing

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependendies 
        run: npm install puppeteer pixelmatch pngjs

      - name: Take Screenshot
        run: node screenshot.js

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Screenshot
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Stage only screenshots directory
          git add screenshots/

          # Avoid failing if nothing changed
          git diff --cached --quiet && echo "No changes to commit" && exit 0

          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "Add screenshot taken at $timestamp"

          # Set remote with token for pushing
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:main
